# Generated by Django 3.2.5 on 2021-07-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cateogry', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=5000)),
                ('answer', models.CharField(max_length=5)),
            ],
        ),
    ]
