# Generated by Django 3.2.5 on 2021-07-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_list',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
