# Generated by Django 3.2.5 on 2021-08-01 06:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_alter_question_list_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_list',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('like', models.BigIntegerField()),
                ('unlike', models.BigIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=5000)),
                ('question_id', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='question_id', to='communication.question_list')),
            ],
        ),
    ]
