# Generated by Django 3.2.5 on 2021-08-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_auto_20210801_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='unlike',
        ),
    ]
