# Generated by Django 3.2.5 on 2021-08-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_auto_20210809_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='unlike',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question_list',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
