# Generated by Django 3.2.5 on 2021-08-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_nickname_list_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='nickname_list',
            name='kakaoid',
            field=models.CharField(default=False, max_length=1000),
        ),
    ]
