# Generated by Django 3.2.5 on 2021-08-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_nickname_list_kakaoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nickname_list',
            name='kakaoid',
            field=models.CharField(max_length=1000),
        ),
    ]
