# Generated by Django 3.2.5 on 2021-08-10 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_authentication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='authentication_id',
            field=models.ForeignKey(db_column='authentication_id', on_delete=django.db.models.deletion.CASCADE, related_name='kakao_id', to='accounts.nickname_list'),
        ),
    ]
