# Generated by Django 3.2.5 on 2021-08-10 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_authentication_authentication_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='authentication_id',
            field=models.ForeignKey(db_column='authentication_id', default=False, on_delete=django.db.models.deletion.CASCADE, related_name='authentication_id', to='accounts.nickname_list'),
        ),
    ]
